name: untitled1
version: '1.0-SNAPSHOT'
main: mee.example.untitled1.Untitled1
api-version: '1.20'

commands:
  mazegen:
    usage: "/<command>"
    description: "迷路の生成"
  key:
    usage: "/<command>"
    description: "ダンジョンスタートの鍵を入手する"
