name: untitled1
version: '1.0-SNAPSHOT'
main: mee.example.untitled1.Untitled1
api-version: '1.20'

commands:
  mazegen:
    usage: "/<command>"
    description: "迷路の生成"
  getpouch:
    usage: "/<command>"
    description: "財布を入手"
